server:
  port: 8082

spring:
  application:
    name: schedule-service
  datasource:
    url: jdbc:postgresql://localhost:5432/justdoit_schedule
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: justdoit-super-secret-key-2024-must-be-at-least-256-bits-long-hs256-ok
